apiVersion: v1
kind: ServiceAccount
metadata:
  name: export-job-sa
  namespace: cnpm-food-delivery
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: export-job-role
  namespace: cnpm-food-delivery
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list"]
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["servicemonitors", "prometheusrules"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: export-job-rolebinding
  namespace: cnpm-food-delivery
subjects:
  - kind: ServiceAccount
    name: export-job-sa
    namespace: cnpm-food-delivery
roleRef:
  kind: Role
  name: export-job-role
  apiGroup: rbac.authorization.k8s.io
