apiVersion: v1
kind: Service
metadata:
  name: client-frontend
  namespace: cnpm-food-delivery
  annotations:
    prometheus.io/scrape: "false"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: client-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
