apiVersion: v1
kind: Service
metadata:
  name: client-frontend
  namespace: cnpm-food-delivery
spec:
  selector:
    app: client-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
