apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: cnpm-food-delivery
  labels:
    app: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: payment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"
            - name: MONGO_PAY_URL
              valueFrom:
                secretKeyRef:
                  name: cnpm-secrets
                  key: MONGO_PAYMENT_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cnpm-secrets
                  key: JWT_SECRET
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: cnpm-secrets
                  key: STRIPE_SECRET_KEY
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: cnpm-secrets
                  key: STRIPE_WEBHOOK_SECRET
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: cnpm-secrets
                  key: TWILIO_ACCOUNT_SID
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cnpm-secrets
                  key: TWILIO_AUTH_TOKEN
            - name: TWILIO_PHONE_NUMBER
              valueFrom:
                secretKeyRef:
                  name: cnpm-secrets
                  key: TWILIO_PHONE_NUMBER
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cnpm-secrets
                  key: RESEND_API_KEY
            - name: ORDER_SERVICE_URL
              value: "http://order-service:5005"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
                    