apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: cnpm-food-delivery
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5002"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: restaurant-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
