apiVersion: v1
kind: Service
metadata:
  name: restaurant-frontend
  namespace: cnpm-food-delivery
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3002"
    prometheus.io/path: "/api/metrics"
spec:
  selector:
    app: restaurant-frontend
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
