apiVersion: v1
kind: Service
metadata:
  name: restaurant-frontend
  namespace: cnpm-food-delivery
spec:
  selector:
    app: restaurant-frontend
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
