version: "3.8"

services:

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-service
    restart: unless-stopped
    ports:
      - "5004:5004"
    environment:
      # In local dev we point at our local mongo container:
      - MONGO_URI=mongodb://localhost:28017/Payment
      # - MONGO_URI=mongodb://mongo:27017/Payment
      - PORT=5004
      - JWT_SECRET=MnAIm95T4VUQWaC591bxkhdmhZDlQk3EP2TFP27YUo65WjRBPxThKVd8PzH0M3wxQB3uX5XvzhYXf8n8jV8Vd8sfUatNPnK1Fo0IBnofLgKKqRWlQoJYBgnWIu3Er0IPB37cshF1KQK3o5r3loXYHBX1BGblU4pdgXZBBLuz5BnpzsSHAEaOQHKWyTEXry5TdkFvEpqXXtT74fZXQz9kJmQceiF8wKyWD1Rx50nyKj08XFx8WlEoOYmUNp8P9IQY

      - STRIPE_SECRET_KEY=sk_test_51S6DRtPb5k3ojf4pxwte7kcvgiEKAwRmyP0Al4BV6tx6nxIuiOz1RIuiaohU6EAyZi4e8gvN1VlaE7GHmYbTSVH800oe00cJMR
      - STRIPE_WEBHOOK_SECRET=whsec_c728fc5c8bf22cd180114a027e3d38be9e3a8b53ddf898f9881a5055302d5571

      - TWILIO_ACCOUNT_SID=AC8e18c3b309c2e704449f62b2ad2a2f38
      - TWILIO_AUTH_TOKEN=fed77310d1b54be7806ce0ccb0615624
      - TWILIO_PHONE_NUMBER=+84356439617

      - RESEND_API_KEY=re_87RJXwsi_7seUntRSnNzyZVdn42DgztiQ
